[variables]
IS_LARAVEL = "yes"
NIXPACKS_PHP_ROOT_DIR = "/app/public"
PORT = "80"

[phases.setup]
nixPkgs = [
    "(php.withExtensions (pe: pe.enabled ++ []))",
    "nginx", 
    "libmysqlclient",
    "phpPackages.composer",
    "nodejs_18",
    "npm-9_x"
]

[phases.install]
cmds = [
    "mkdir -p /var/log/nginx && mkdir -p /var/cache/nginx",
    "composer install --optimize-autoloader --no-dev",
    "npm ci"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "php-fpm -F & nginx -g 'daemon off;'"